- name: variables
  hosts: localhost
  vars:
    course: "Devops"
    trainer: "Sivakumar"
    duration: "3 months"
  tasks:
  - name: variables with task
    vars:
     course: "ansible"
    ansible.builtin.debug:
      msg: "i am learning {{course}} course, trainer is {{trainer}} and course duration is {{duration}}"

  - name: variables with task
    ansible.builtin.debug:
      msg: "i am learning {{course}} course, trainer is {{trainer}} and course duration is {{duration}}"