- name: variables with files
  hosts: localhost
  vars_files:
  - vars.yaml
  tasks:
  - name: variables with task
    vars:
     course: "ansible"
    ansible.builtin.debug:
      msg: "i am learning {{course}} course, trainer is {{trainer}} and course duration is {{duration}}"
