- name: variables from prompts
  hosts: localhost
  vars_prompts:
  - name: USERNAME
    prompt: please enter the username
    private: false
  - name: PASSWORD
    prompt: please enter the username
    private: true
  tasks:
  - name: variables with task
    vars:
     course: "ansible"
    ansible.builtin.debug:
      msg: " Please login with username {{USERNAME}} and enter {{PASSWORD}} "
