- name: varaiables from inventory
  hosts: localhost
  tasks:
  - name: variales from inventory
    ansible.builtin.debug:
      msg: "i am learning {{course}} course, trainer is {{trainer}} and course duration is {{duration}}"
