- name: varaiables from arguments
  hosts: localhost
  tasks:
  - name: variales from args
    ansible.builtin.debug:
      msg: "i am learning {{course}} course, trainer is {{trainer}} and course duration is {{duration}}"
