- name: variables from arguments
  hosts: localhost
  vars:
    course: "Devopsvars"
  vars_file:
  - vars.yaml
  vars_prompt: 
  - name: course
    prompt: enter course name
    private: false
  tasks:
  - name: variales from args
    vars:
      course: "Devopstask"
    ansible.builtin.debug:
      msg: "i am learning {{course}} course."
