- name: data types
  hosts: localhost
  vars:
    Course: "Devops with aws"
    Tools:
    - Sivakumar
    - duration
    - 3 months
    Experience:
      trainer: "sivakumar"
      course: "Devops"
      duration: "120 hours"
    Realproject: true
  tasks:
  - name: print data types
    ansible.builtin.debug:
      msg: "I am learning {{Course}}, from {{Tools}}, and experiance is {{Experience}}, with real projects {{Realproject}}"