- name: filter
  hosts: localhost
  tasks:
  - name: vdefault
    ansible.builtin.debug:
      msg: "i am learning {{course | default('ansible')}} course"

- name: Upper case
  hosts: localhost
  vars:
    course: "Devops Upper"
  tasks:
  - name: vdefault
    ansible.builtin.debug:
      msg: "i am learning {{course | upper }} course"

- name: Lower
  hosts: localhost
  vars:
    course: "Devops Lowerr"
  tasks:
  - name: vdefault
    ansible.builtin.debug:
      msg: "i am learning {{course | lower }} course"

- name: Duplicates
  hosts: localhost
  vars:
    numbers: [1, 2, 2, 3, 4, 5, 5]
  tasks:
  - name: remove duplicates
    ansible.builtin.debug:
      msg: "{{ numbers | unique }}"

- name: Min and Max values
  hosts: localhost
  vars:
    ages: [21, 33, 45, 56, 89]
  tasks:
  - name: print Min and Max values
    ansible.builtin.debug:
      msg: " Minimum age is: {{ ages | min }}, Maximum age is: {{ ages | max }}"