- name: loops
  hosts: localhost
  tasks:
  - name: print the items
    ansible.builtin.debug:
      msg: " print the items {{ item }}"
    loop:
    - siva
    - subbu
    - kumar

- name: loops
  hosts: localhost
  tasks:
  - name: install packages
    ansible.builtin.dnf:
      name: {{ item }}
      state: latest
    loop:
    - mysql
    - nginx
    - postfix