- name: loops
  hosts: localhost
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.dnf:
      name: "{{ item.name }}"
      state: l"{{ item.state }}"
    loop:
    - { name: 'mysql' state: 'present' }
    - { name: 'nginx' state: 'absent' }
    - { name: 'postfix' state: 'absent' }